# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "A Software developer's blog :P"
description: > # this means to ignore newlines until "email:"
   This blog is my journey to the development world. You will find about open source, projects on C++, Javascript, python and others.

email: garvitdelhi@gmail.com
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/header.jpg"

name: 'Garvit Khatri'
author: 'Garvit Khatri'
author_image: "/assets/images/author_image.jpg"

paginate:	2

url: "https://garvitdelhi.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@garvitdelhi'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/garvitdelhi
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/garvitdelhi
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/garvitdelhi
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://google.com/garvitdelhi
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:
