plugins:
    - jemoji
    - jekyll-paginate

title: Garvit Khatri
description: My Personal Blog
paginate: 5
url: "https://garvit.in"
baseurl: ""

exclude:
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - THEME-LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      sitemap: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
        path: ''
        type: "tags"
    values:
        permalink: "/tag/:slug/"
        layout: "tag"
        tag: "Tech"

collections:
    tags:
        title: "Tags"
        output: true

email: garvitdelhi@gmail.com
logo: "/assets/images/logo.png"
cover: "/assets/images/header.jpg"
cover_description: "Photo by Glenn Carstens-Peters on Unsplash"
cover_credits: "<a style=\"background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px;\" href=\"https://unsplash.com/@glenncarstenspeters?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge\" target=\"_blank\" rel=\"noopener noreferrer\" title=\"Download free do whatever you want high-resolution photos from Glenn Carstens-Peters\"><span style=\"display:inline-block;padding:2px 3px;\"><svg xmlns=\"http://www.w3.org/2000/svg\" style=\"height:12px;width:auto;position:relative;vertical-align:middle;top:-1px;fill:white;\" viewBox=\"0 0 32 32\"><title></title><path d=\"M20.8 18.1c0 2.7-2.2 4.8-4.8 4.8s-4.8-2.1-4.8-4.8c0-2.7 2.2-4.8 4.8-4.8 2.7.1 4.8 2.2 4.8 4.8zm11.2-7.4v14.9c0 2.3-1.9 4.3-4.3 4.3h-23.4c-2.4 0-4.3-1.9-4.3-4.3v-15c0-2.3 1.9-4.3 4.3-4.3h3.7l.8-2.3c.4-1.1 1.7-2 2.9-2h8.6c1.2 0 2.5.9 2.9 2l.8 2.4h3.7c2.4 0 4.3 1.9 4.3 4.3zm-8.6 7.5c0-4.1-3.3-7.5-7.5-7.5-4.1 0-7.5 3.4-7.5 7.5s3.3 7.5 7.5 7.5c4.2-.1 7.5-3.4 7.5-7.5z\"></path></svg></span><span style=\"display:inline-block;padding:2px 3px;\">Glenn Carstens-Peters</span></a>"

google_analytics_tracking_id: UA-56536075-2

name: 'Garvit Khatri'
author: 'Garvit Khatri'
author_image: "/assets/images/author_image.jpg"
twitter: garvitdelhi

social:
  - icon: twitter
    url: https://twitter.com/garvitdelhi
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/garvitdelhi
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	facebook
    url:	https://facebook.com/garvitdelhi
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
