# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "A Software developer's blog :P"
description: > # this means to ignore newlines until "email:"
   This blog is my journey to the development world. You will find about open source, projects on C++, Javascript, python and others.

email: garvitdelhi@gmail.com
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/head.jpg"
cover_description: "Photo by Thought Catalog on Unsplash"
cover_credits: "<a style=\"background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px;\" href=\"https://unsplash.com/@thoughtcatalog?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge\" target=\"_blank\" rel=\"noopener noreferrer\" title=\"Download free do whatever you want high-resolution photos from Thought Catalog\"><span style=\"display:inline-block;padding:2px 3px;\"><svg xmlns=\"http://www.w3.org/2000/svg\" style=\"height:12px;width:auto;position:relative;vertical-align:middle;top:-1px;fill:white;\" viewBox=\"0 0 32 32\"><title></title><path d=\"M20.8 18.1c0 2.7-2.2 4.8-4.8 4.8s-4.8-2.1-4.8-4.8c0-2.7 2.2-4.8 4.8-4.8 2.7.1 4.8 2.2 4.8 4.8zm11.2-7.4v14.9c0 2.3-1.9 4.3-4.3 4.3h-23.4c-2.4 0-4.3-1.9-4.3-4.3v-15c0-2.3 1.9-4.3 4.3-4.3h3.7l.8-2.3c.4-1.1 1.7-2 2.9-2h8.6c1.2 0 2.5.9 2.9 2l.8 2.4h3.7c2.4 0 4.3 1.9 4.3 4.3zm-8.6 7.5c0-4.1-3.3-7.5-7.5-7.5-4.1 0-7.5 3.4-7.5 7.5s3.3 7.5 7.5 7.5c4.2-.1 7.5-3.4 7.5-7.5z\"></path></svg></span><span style=\"display:inline-block;padding:2px 3px;\">Thought Catalog</span></a>"

name: 'Garvit Khatri'
author: 'Garvit Khatri'
author_image: "/assets/images/author_image.jpg"

paginate: 5

url: "https://garvitdelhi.github.io" # the base hostname & protocol for your site
# url: "http://0.0.0.0:4000/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@garvitdelhi'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-56536075-2

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/garvitdelhi
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/garvitdelhi
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/garvitdelhi
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://google.com/garvitdelhi
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:
